// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvmK5xhI6SbDRx8cXouSJnN_mckBUpOFY',
    appId: '1:438933666649:web:1707b10091fe2ebf70aa48',
    messagingSenderId: '438933666649',
    projectId: 'pokedexapp-4071f',
    authDomain: 'pokedexapp-4071f.firebaseapp.com',
    storageBucket: 'pokedexapp-4071f.firebasestorage.app',
    measurementId: 'G-CDTR723DRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1VYr0Rn9dFESNpWhgO2--83DKDS9drHk',
    appId: '1:438933666649:android:05668017d04b93fa70aa48',
    messagingSenderId: '438933666649',
    projectId: 'pokedexapp-4071f',
    storageBucket: 'pokedexapp-4071f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGx7aw5egzLJiSrv5K9_KTkqFCqBJPmjA',
    appId: '1:438933666649:ios:068806de3083651370aa48',
    messagingSenderId: '438933666649',
    projectId: 'pokedexapp-4071f',
    storageBucket: 'pokedexapp-4071f.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGx7aw5egzLJiSrv5K9_KTkqFCqBJPmjA',
    appId: '1:438933666649:ios:068806de3083651370aa48',
    messagingSenderId: '438933666649',
    projectId: 'pokedexapp-4071f',
    storageBucket: 'pokedexapp-4071f.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvmK5xhI6SbDRx8cXouSJnN_mckBUpOFY',
    appId: '1:438933666649:web:667c18a678468c9c70aa48',
    messagingSenderId: '438933666649',
    projectId: 'pokedexapp-4071f',
    authDomain: 'pokedexapp-4071f.firebaseapp.com',
    storageBucket: 'pokedexapp-4071f.firebasestorage.app',
    measurementId: 'G-ZHMNCC96WY',
  );
}
